INSERT INTO "group" (gID,name,"limit",description) VALUES (1,'Berwick-upon-Tweed',8,'convallis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (2,'McCallum',5,'Vivamus nisi. Mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (3,'Gjoa Haven',6,'non, luctus sit amet,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (4,'Stendal',7,'et malesuada');
INSERT INTO "group" (gID,name,"limit",description) VALUES (5,'Buckie',9,'diam. Proin dolor. Nulla');
INSERT INTO "group" (gID,name,"limit",description) VALUES (6,'Collecchio',6,'accumsan sed, facilisis vitae, orci.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (7,'Trazegnies',9,'orci lobortis augue scelerisque mollis. Phasellus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (8,'Oliver',6,'ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (9,'Salles',8,'vitae mauris sit amet lorem semper auctor. Mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (10,'Yeovil',7,'lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non');
INSERT INTO "group" (gID,name,"limit",description) VALUES (11,'Kızılcahamam',5,'pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet');
INSERT INTO "group" (gID,name,"limit",description) VALUES (12,'Wokingham',6,'semper erat, in consectetuer ipsum nunc');
INSERT INTO "group" (gID,name,"limit",description) VALUES (13,'San Diego',8,'auctor odio a');
INSERT INTO "group" (gID,name,"limit",description) VALUES (14,'Newmarket',5,'non arcu. Vivamus sit amet risus. Donec');
INSERT INTO "group" (gID,name,"limit",description) VALUES (15,'Salihli',5,'nec');
INSERT INTO "group" (gID,name,"limit",description) VALUES (16,'Meerle',8,'commodo ipsum.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (17,'Hualpén',6,'Praesent interdum ligula eu enim. Etiam imperdiet dictum magna.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (18,'Stockton-on-Tees',6,'mauris, rhoncus id, mollis nec, cursus a, enim.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (19,'Loncoche',8,'commodo ipsum. Suspendisse non leo. Vivamus nibh');
INSERT INTO "group" (gID,name,"limit",description) VALUES (20,'Mandurah',8,'Phasellus ornare. Fusce mollis. Duis sit amet diam eu');
INSERT INTO "group" (gID,name,"limit",description) VALUES (21,'Freital',5,'dignissim tempor arcu. Vestibulum ut eros non');
INSERT INTO "group" (gID,name,"limit",description) VALUES (22,'Meugliano',9,'est. Mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (23,'Westmalle',7,'scelerisque dui. Suspendisse ac metus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (24,'Béthune',10,'tellus eu augue porttitor interdum. Sed');
INSERT INTO "group" (gID,name,"limit",description) VALUES (25,'Bulzi',10,'Nunc sed orci lobortis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (26,'Seattle',9,'ac mattis semper, dui lectus rutrum urna, nec');
INSERT INTO "group" (gID,name,"limit",description) VALUES (27,'San Isidro',9,'interdum. Sed auctor odio a purus. Duis elementum, dui');
INSERT INTO "group" (gID,name,"limit",description) VALUES (28,'João Pessoa',7,'placerat, orci lacus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (29,'Arles',9,'dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (30,'Traun',10,'Cras');
INSERT INTO "group" (gID,name,"limit",description) VALUES (31,'Banda',9,'pede, ultrices a, auctor non, feugiat nec, diam. Duis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (32,'Miramichi',10,'diam at pretium aliquet, metus urna convallis erat, eget');
INSERT INTO "group" (gID,name,"limit",description) VALUES (33,'Castlegar',5,'et magnis dis parturient');
INSERT INTO "group" (gID,name,"limit",description) VALUES (34,'Leers-et-Fosteau',6,'lobortis tellus justo sit amet nulla. Donec non justo. Proin');
INSERT INTO "group" (gID,name,"limit",description) VALUES (35,'Koszalin',10,'justo sit amet nulla. Donec non justo. Proin non');
INSERT INTO "group" (gID,name,"limit",description) VALUES (36,'Minto',5,'amet, risus. Donec');
INSERT INTO "group" (gID,name,"limit",description) VALUES (37,'Wellingborough',9,'orci, consectetuer');
INSERT INTO "group" (gID,name,"limit",description) VALUES (38,'Coalhurst',9,'convallis, ante lectus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (39,'Monticelli d''Ongina',8,'magna et ipsum cursus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (40,'Bergisch Gladbach',5,'elit');
INSERT INTO "group" (gID,name,"limit",description) VALUES (41,'Manukau',8,'ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (42,'Essex',7,'imperdiet dictum magna. Ut tincidunt orci quis lectus.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (43,'Nanterre',7,'eget');
INSERT INTO "group" (gID,name,"limit",description) VALUES (44,'Hoogeveen',10,'nec tempus mauris erat eget');
INSERT INTO "group" (gID,name,"limit",description) VALUES (45,'Morpeth',5,'lobortis. Class aptent');
INSERT INTO "group" (gID,name,"limit",description) VALUES (46,'Pfungstadt',7,'Sed eu eros. Nam consequat dolor');
INSERT INTO "group" (gID,name,"limit",description) VALUES (47,'Regina',9,'Curabitur');
INSERT INTO "group" (gID,name,"limit",description) VALUES (48,'Essex',9,'eu, placerat eget, venenatis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (49,'Beez',9,'egestas. Fusce aliquet magna a neque. Nullam ut nisi a');
INSERT INTO "group" (gID,name,"limit",description) VALUES (50,'Penna San Giovanni',6,'interdum feugiat. Sed nec metus facilisis lorem');
INSERT INTO "group" (gID,name,"limit",description) VALUES (51,'La Reina',7,'risus. Nunc ac sem ut dolor dapibus gravida. Aliquam');
INSERT INTO "group" (gID,name,"limit",description) VALUES (52,'La Granja',10,'nulla at sem');
INSERT INTO "group" (gID,name,"limit",description) VALUES (53,'Belfort',9,'Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (54,'Ostrowiec Świętokrzyski',6,'adipiscing non, luctus sit amet, faucibus ut, nulla. Cras');
INSERT INTO "group" (gID,name,"limit",description) VALUES (55,'San Diego',6,'sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices');
INSERT INTO "group" (gID,name,"limit",description) VALUES (56,'Sheffield',10,'massa. Quisque porttitor');
INSERT INTO "group" (gID,name,"limit",description) VALUES (57,'Brandon',6,'sit amet nulla. Donec non justo. Proin non');
INSERT INTO "group" (gID,name,"limit",description) VALUES (58,'Sacramento',9,'pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer');
INSERT INTO "group" (gID,name,"limit",description) VALUES (59,'Koolkerke',10,'arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras');
INSERT INTO "group" (gID,name,"limit",description) VALUES (60,'Meerdonk',8,'consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam');
INSERT INTO "group" (gID,name,"limit",description) VALUES (61,'Mira Bhayandar',5,'non');
INSERT INTO "group" (gID,name,"limit",description) VALUES (62,'Linares',8,'penatibus et magnis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (63,'Sivry-Rance',9,'Duis mi enim, condimentum eget, volutpat ornare,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (64,'Pontedera',7,'ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (65,'Portland',9,'diam luctus lobortis. Class aptent taciti sociosqu');
INSERT INTO "group" (gID,name,"limit",description) VALUES (66,'Sunset Point',9,'Phasellus at augue id ante dictum cursus. Nunc mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (67,'Gandhinagar',5,'purus. Maecenas libero');
INSERT INTO "group" (gID,name,"limit",description) VALUES (68,'Thurso',8,'fringilla purus mauris a nunc. In at pede. Cras vulputate');
INSERT INTO "group" (gID,name,"limit",description) VALUES (69,'Mission',10,'ligula. Nullam enim.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (70,'Juneau',8,'sed, est. Nunc laoreet');
INSERT INTO "group" (gID,name,"limit",description) VALUES (71,'Darlington',9,'et, rutrum non, hendrerit id, ante. Nunc mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (72,'Bonnyville Municipal District',10,'metus. Aenean sed pede');
INSERT INTO "group" (gID,name,"limit",description) VALUES (73,'Parchim City',10,'a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc');
INSERT INTO "group" (gID,name,"limit",description) VALUES (74,'Brahmapur',8,'tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac');
INSERT INTO "group" (gID,name,"limit",description) VALUES (75,'Bekkerzeel',10,'risus. In mi');
INSERT INTO "group" (gID,name,"limit",description) VALUES (76,'Besançon',6,'sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (77,'Kanpur Cantonment',9,'ullamcorper eu, euismod ac,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (78,'Pescantina',10,'tortor');
INSERT INTO "group" (gID,name,"limit",description) VALUES (79,'Veenendaal',8,'eu, eleifend nec, malesuada ut, sem. Nulla');
INSERT INTO "group" (gID,name,"limit",description) VALUES (80,'Carstairs',6,'orci. Phasellus dapibus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (81,'Pugwash',9,'dolor, nonummy ac, feugiat non, lobortis quis,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (82,'Liverpool',6,'Pellentesque habitant morbi tristique senectus');
INSERT INTO "group" (gID,name,"limit",description) VALUES (83,'Bhilai',6,'turpis. Aliquam adipiscing lobortis risus. In');
INSERT INTO "group" (gID,name,"limit",description) VALUES (84,'Hanau',7,'nunc est, mollis non, cursus non, egestas a, dui. Cras');
INSERT INTO "group" (gID,name,"limit",description) VALUES (85,'Folkestone',7,'Fusce aliquet magna a neque. Nullam ut nisi a odio');
INSERT INTO "group" (gID,name,"limit",description) VALUES (86,'Greater Sudbury',7,'Curae;');
INSERT INTO "group" (gID,name,"limit",description) VALUES (87,'Forchies-la-Marche',10,'a tortor. Nunc commodo');
INSERT INTO "group" (gID,name,"limit",description) VALUES (88,'Avelgem',9,'Mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (89,'Bremen',5,'nisi nibh lacinia orci, consectetuer euismod est arcu ac');
INSERT INTO "group" (gID,name,"limit",description) VALUES (90,'Genzano di Lucania',10,'ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris');
INSERT INTO "group" (gID,name,"limit",description) VALUES (91,'Stratford-upon-Avon',10,'tincidunt, nunc ac');
INSERT INTO "group" (gID,name,"limit",description) VALUES (92,'Waarmaarde',8,'velit justo nec ante. Maecenas mi felis, adipiscing fringilla,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (93,'Hartford',9,'dictum placerat,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (94,'Raj Nandgaon',5,'Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (95,'Ingraj Bazar',5,'elit, pellentesque a, facilisis');
INSERT INTO "group" (gID,name,"limit",description) VALUES (96,'Cartago',5,'consequat nec,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (97,'Hertford',6,'Etiam ligula tortor, dictum eu,');
INSERT INTO "group" (gID,name,"limit",description) VALUES (98,'Woodlands County',6,'cursus. Integer mollis. Integer tincidunt aliquam arcu.');
INSERT INTO "group" (gID,name,"limit",description) VALUES (99,'San Antonio',9,'Donec egestas. Aliquam nec enim. Nunc');
INSERT INTO "group" (gID,name,"limit",description) VALUES (100,'Lissewege',5,'Maecenas mi felis, adipiscing fringilla, porttitor');